### PR TITLE
chore: ci updates and style change

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you drop support for Node 8.x? It's not supported by ElasticSearch anymore.

**Comment by Fdawgs** [comment]
@mcollina, will do! Would it be worth also adding the latest LTS, v14?

I'm guessing this will require a major semver bump?

**Comment by mcollina** [comment]
Go add v14. We should bump the major.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
(you should be able to merge)

**Pull request merged**
