### PR TITLE
chore: update plugins-ci-elasticsearch.yml reference to v5.0.0

### PR DESCRIPTION
**Pull request by tpreviero**
Updates `plugins-ci-elasticsearch.yml` to version `v5.0.0`.

#### Checklist

- [x] run `npm run test` ~and `npm run benchmark`~ no benchmarks
- [x] tests ~and/or benchmarks~ are included no benchmarks
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — APPROVED** [review]

**Review by dancastillo — APPROVED** [review]
LGTM

**Review by gurgunday — CHANGES_REQUESTED** [review]
I was going to look at this but CI is red

**Comment by tpreviero** [comment]
> I was going to look at this but CI is red

Apparently the image `elasticsearch:8.13.2`, [which is the one being currently used](https://github.com/fastify/workflows/blob/main/.github/workflows/plugins-ci-elasticsearch.yml#L107), is [not present on Docker Hub](https://hub.docker.com/_/elasticsearch/tags?name=8.13).
We would need to update that docker image version.

**Comment by tpreviero** [comment]
> > I was going to look at this but CI is red
> 
> Apparently the image `elasticsearch:8.13.2`, [which is the one being currently used](https://github.com/fastify/workflows/blob/main/.github/workflows/plugins-ci-elasticsearch.yml#L107), is [not present on Docker Hub](https://hub.docker.com/_/elasticsearch/tags?name=8.13). We would need to update that docker image version.

Opened https://github.com/fastify/workflows/pull/136 to tackle this.

**Comment by tpreviero** [comment]
As `v5.0.0` version of https://github.com/fastify/workflows contains an elasticsearch image version that is not on Docker Hub, closing this in favour of https://github.com/fastify/fastify-elasticsearch/pull/119.

**Pull request closed without merging**
